//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EparchyDBB.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EparchyEntities : DbContext
    {
        public EparchyEntities()
            : base("name=EparchyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Church> Churches { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<SpiritualMinister> SpiritualMinisters { get; set; }
        public virtual DbSet<YouthConvention> YouthConventions { get; set; }
    }
}
