//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EparchyDBB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpiritualMinister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpiritualMinister()
        {
            this.events = new HashSet<@event>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Last_Name { get; set; }
        public string Holy_orders { get; set; }
        public string Number { get; set; }
        public Nullable<int> IdChurch { get; set; }
    
        public virtual Church Church { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@event> events { get; set; }
    }
}
